#include "PipeWireClient.hpp"

#include <drm/drm_fourcc.h>
#include <spa/pod/vararg.h>
#include <unistd.h>

#ifdef HAVE_EGL
#include "../../utils/linux/OpenGlUtils.hpp"
#endif

PipeWireClient::PipeWireClient() {
  pw_init(nullptr, nullptr);
  std::println("[PipeWireClient] Library initialized");
}

PipeWireClient::~PipeWireClient() {
  disconnect();
  pw_deinit();
}

bool PipeWireClient::connect(int fd, uint32_t node_id,
                             std::function<void(const VideoFrame&)> callback) {
  onFrameCallback = callback;
  this->fd = fd;

  if (!startLoop()) return false;
  if (!configureCore()) return false;
  configureStream();
  negotiateFormat(node_id);
  onConfigureEnd();

  return true;
}

bool PipeWireClient::startLoop() {
  // Create a thread for PipeWire to process video packages and to not block our
  // main thread
  loop = pw_thread_loop_new("pipewire-capture-loop", nullptr);
  context = pw_context_new(
      pw_thread_loop_get_loop(loop), nullptr,
      0);  // Manages memory, modules and plugins from our application side
  if (!(loop && context)) return false;

  // Starts the PipeWire thread and immediately locks it, so it does not crash
  // while we configure the format
  pw_thread_loop_start(loop);
  pw_thread_loop_lock(loop);
  return true;
}

bool PipeWireClient::configureCore() {
  // Tells context to connect with our File Descriptor. Duplicates it so we do
  // not lose reference in case PipeWire thread closes it
  core = pw_context_connect_fd(context, dup(fd), nullptr, 0);
  if (!core) {
    pw_thread_loop_unlock(loop);
    return false;
  }

  coreEvents.version = PW_VERSION_CORE_EVENTS;
  coreEvents.error = onCoreError;
  pw_core_add_listener(core, &coreListener, &coreEvents, this);
  return true;
}

void PipeWireClient::configureStream() {
  // PipeWire manages media (audio, video, sound...). Here we define we want
  // video management for node_id target
  pw_properties* props =
      pw_properties_new(PW_KEY_MEDIA_TYPE, "Video", PW_KEY_MEDIA_CATEGORY,
                        "Capture", PW_KEY_MEDIA_ROLE, "Screen", nullptr);

  // Creates the communication channel
  stream = pw_stream_new(core, "RemoteDesktop Capture Stream", props);
  streamEvents.version = PW_VERSION_STREAM_EVENTS;

  // Listeners
  streamEvents.state_changed = onStreamStateChanged;
  streamEvents.param_changed = onStreamParamChanged;
  streamEvents.process = onStreamProcess;  // Registers the event triggered on
                                           // each frame generated by the GPU
  pw_stream_add_listener(stream, &streamListener, &streamEvents, this);
}

std::vector<uint64_t> PipeWireClient::getModifiers() {
  std::vector<uint64_t> modifiers;

#ifdef HAVE_EGL
  auto eglDisplay = OpenGlUtils::getEglDisplay();
  if (eglDisplay != EGL_NO_DISPLAY) {
    modifiers =
        OpenGlUtils::getSupportedModifiers(eglDisplay, DRM_FORMAT_XRGB8888);
  }
#elifdef HAVE_VULKAN
  // TODO: Add Vulkan equivalent logic here if modifiers are still empty
#endif

  return modifiers;
}

void PipeWireClient::negotiateFormat(uint32_t node_id) {
  auto modifiers = getModifiers();
  uint8_t buffer[1024];
  spa_pod_builder b = SPA_POD_BUILDER_INIT(buffer, sizeof(buffer));

  spa_pod_frame f[2];
  // Start Object
  spa_pod_builder_push_object(&b, &f[0], SPA_TYPE_OBJECT_Format,
                              SPA_PARAM_EnumFormat);

  spa_pod_builder_add(
      &b, SPA_FORMAT_mediaType, SPA_POD_Id(SPA_MEDIA_TYPE_video),
      SPA_FORMAT_mediaSubtype, SPA_POD_Id(SPA_MEDIA_SUBTYPE_raw),
      SPA_FORMAT_VIDEO_format,
      SPA_POD_CHOICE_ENUM_Id(5, SPA_VIDEO_FORMAT_BGRx, SPA_VIDEO_FORMAT_BGRx,
                             SPA_VIDEO_FORMAT_RGBx, SPA_VIDEO_FORMAT_BGRA,
                             SPA_VIDEO_FORMAT_RGBA),
      0);

  spa_pod_builder_prop(
      &b, SPA_FORMAT_VIDEO_modifier,
      SPA_POD_PROP_FLAG_MANDATORY | SPA_POD_PROP_FLAG_DONT_FIXATE);
  spa_pod_builder_push_choice(&b, &f[1], SPA_CHOICE_Enum, 0);

  // First item must be the preferred choice
  spa_pod_builder_long(&b, modifiers[0]);
  // Then list all choices (including the preferred one again)
  for (auto mod : modifiers) spa_pod_builder_long(&b, mod);

  spa_pod_builder_pop(&b, &f[1]);

  // End Object 1 (DMA-BUF Linear)
  const spa_pod* param =
      static_cast<const spa_pod*>(spa_pod_builder_pop(&b, &f[0]));

  // Start Object 2 (MemFd Fallback without Modifiers)
  spa_pod_builder_push_object(&b, &f[0], SPA_TYPE_OBJECT_Format,
                              SPA_PARAM_EnumFormat);
  spa_pod_builder_add(
      &b, SPA_FORMAT_mediaType, SPA_POD_Id(SPA_MEDIA_TYPE_video),
      SPA_FORMAT_mediaSubtype, SPA_POD_Id(SPA_MEDIA_SUBTYPE_raw),
      SPA_FORMAT_VIDEO_format,
      SPA_POD_CHOICE_ENUM_Id(5, SPA_VIDEO_FORMAT_BGRx, SPA_VIDEO_FORMAT_BGRx,
                             SPA_VIDEO_FORMAT_RGBx, SPA_VIDEO_FORMAT_BGRA,
                             SPA_VIDEO_FORMAT_RGBA),
      0);
  const spa_pod* param2 =
      static_cast<const spa_pod*>(spa_pod_builder_pop(&b, &f[0]));

  const struct spa_pod* params[2] = {param, param2};

  // Connecting to the stream.
  pw_stream_connect(stream, PW_DIRECTION_INPUT, node_id,
                    PW_STREAM_FLAG_AUTOCONNECT, params, 2);
}

void PipeWireClient::onConfigureEnd() {
  pw_thread_loop_unlock(loop);
  std::println("✅ [PipeWire] Stream created, format requested...");
}

void PipeWireClient::disconnect() {
  if (loop) pw_thread_loop_stop(loop);
  if (stream) {
    pw_stream_disconnect(stream);
    pw_stream_destroy(stream);
    stream = nullptr;
  }
  if (core) {
    pw_core_disconnect(core);
    core = nullptr;
  }
  if (context) {
    pw_context_destroy(context);
    context = nullptr;
  }
  if (loop) {  // We need to destroy everything else first wit the loop paused
    pw_thread_loop_destroy(loop);
    loop = nullptr;
  }
}

void PipeWireClient::onCoreError(void* /*data*/, uint32_t id, int /*seq*/,
                                 int /*res*/, const char* message) {
  std::println(stderr, "❌ [PipeWire] Core critial error (id:{}): {}", id,
               message);
}

void PipeWireClient::onStreamStateChanged(void* data, pw_stream_state old_state,
                                          pw_stream_state state,
                                          const char* error) {
  constexpr auto state_name = [](pw_stream_state s) {
    switch (s) {
      case PW_STREAM_STATE_ERROR:
        return "ERROR";
      case PW_STREAM_STATE_UNCONNECTED:
        return "UNCONNECTED";
      case PW_STREAM_STATE_CONNECTING:
        return "CONNECTING";
      case PW_STREAM_STATE_PAUSED:
        return "PAUSED";
      case PW_STREAM_STATE_STREAMING:
        return "STREAMING";
      default:
        return "UNKNOWN";
    }
  };
  std::println("🌊 [PipeWire] Stream state changed: {} -> {}",
               state_name(old_state), state_name(state));

  PipeWireClient* self = static_cast<PipeWireClient*>(data);

  if (state == PW_STREAM_STATE_PAUSED) pw_stream_set_active(self->stream, true);
  if (state == PW_STREAM_STATE_ERROR && self->context != nullptr)
    std::println(stderr, "❌ [PipeWire] Error at Stream: {}",
                 error ? error : "Unknown");
}

// Called after Wayland accepted the video format config and before GPU sent the
// first frame connect() -> state changed to 'CONNECTING' -> PipeWire gets the
// request and accepts it -> onStreamParamChanged() -> instantiate encoder
void PipeWireClient::onStreamParamChanged(void* data, uint32_t id,
                                          const spa_pod* param) {
  PipeWireClient* self = static_cast<PipeWireClient*>(data);
  std::println(
      "🔍 [PipeWireClient] onStreamParamChanged called with id: {}, param is "
      "null: {}",
      id, param == nullptr);

  // We only care about the Format parameter
  if (param == nullptr || id != SPA_PARAM_Format) return;

  struct spa_video_info_raw info;
  if (int ret = spa_format_video_raw_parse(param, &info); ret < 0) {
    std::println("[PipeWireClient] Error parsing video format. Code: {}", ret);
    return;
  }

  self->width = info.size.width;
  self->height = info.size.height;
  self->format = info.format;
  self->fps = (info.framerate.denom > 0 && info.framerate.num > 0)
                  ? info.framerate.num / info.framerate.denom
                  : 144;
  self->drmModifier = info.modifier;
  std::println(
      "🔍 [PipeWireClient] Negotiated format: {}x{} at {}fps, modifier: {}",
      self->width, self->height, self->fps, self->drmModifier);

  uint8_t buffer[1024];
  spa_pod_builder b = SPA_POD_BUILDER_INIT(buffer, sizeof(buffer));

  const struct spa_pod* params[1];
  // Explicitly request DMA-BUF from the allocator now that formats are fixed
  params[0] = static_cast<spa_pod*>(spa_pod_builder_add_object(
      &b, SPA_TYPE_OBJECT_ParamBuffers, SPA_PARAM_Buffers,
      SPA_PARAM_BUFFERS_buffers, SPA_POD_CHOICE_RANGE_Int(8, 2, 32),
      SPA_PARAM_BUFFERS_blocks, SPA_POD_CHOICE_RANGE_Int(1, 1, 4),
      SPA_PARAM_BUFFERS_size,
      SPA_POD_CHOICE_RANGE_Int(self->width * self->height * 4,
                               self->width * self->height * 4, INT32_MAX),
      SPA_PARAM_BUFFERS_stride,
      SPA_POD_CHOICE_RANGE_Int(self->width * 4, self->width * 4, INT32_MAX),
      SPA_PARAM_BUFFERS_dataType,
      SPA_POD_CHOICE_FLAGS_Int((1 << SPA_DATA_DmaBuf))));  // Supported Option 2
  // Send the acceptance back to PipeWire
  pw_stream_update_params(self->stream, params, 1);
  pw_stream_set_active(self->stream, true);
}

// Called once every frame
void PipeWireClient::onStreamProcess(void* data) {
  PipeWireClient* self = static_cast<PipeWireClient*>(data);
  struct pw_buffer* b = pw_stream_dequeue_buffer(self->stream);
  if (!b) return;

  struct spa_buffer* buf = b->buffer;
  if (!buf || buf->n_datas == 0 || !buf->datas[0].chunk) {
    pw_stream_queue_buffer(self->stream, b);
    return;
  }
  VideoFrame frame = {
      .type = FrameMemoryType::MemFd,
      .fd = dup(buf->datas[0].fd),
      .width = self->width,
      .height = self->height,
      .stride = static_cast<uint32_t>(buf->datas[0].chunk->stride),
      .fps = self->fps,
      .spaFormat = self->format,
      .drmModifier = self->drmModifier};

  frame.size = buf->datas[0].maxsize;

  if (buf->datas[0].chunk->size == 0) {
    pw_stream_queue_buffer(self->stream, b);
    return;
  }

  switch (buf->datas[0].type) {
    case SPA_DATA_DmaBuf:
    case SPA_ID_INVALID:
      frame.type = FrameMemoryType::DmaBuf;
      break;
    case SPA_DATA_MemFd:
      frame.type = FrameMemoryType::MemFd;
      break;
    case SPA_DATA_MemPtr:
      frame.type = FrameMemoryType::MemPtr;
      frame.data = (uint8_t*)buf->datas[0].data;
      frame.size = buf->datas[0].chunk->size;
      break;
    default:
      std::println("⚠️ [PipeWireClient] Unknown frame memory type: {}",
                   buf->datas[0].type);
      frame.type = FrameMemoryType::MemFd;  // fallback
      break;
  }

  if (frame.type == FrameMemoryType::DmaBuf) {
    static int frameCount = 0;
    frameCount++;
    if (frameCount == 1 || frameCount % frame.fps == 0) {
      std::println(
          "🔍 [PipeWireClient] (Frame {}) Captured DmaBuf frame and sending to "
          "BaseEncoder...",
          frameCount);
    }
  } else if (frame.type == FrameMemoryType::MemFd) {
    static int frameCountMemFd = 0;
    frameCountMemFd++;
    if (frameCountMemFd == 1 || frameCountMemFd % frame.fps == 0) {
      std::println(
          "🔍 [PipeWireClient] (Frame {}) Captured MemFd frame and sending to "
          "BaseEncoder...",
          frameCountMemFd);
    }
  }

  if (self->onFrameCallback) self->onFrameCallback(frame);

  pw_stream_queue_buffer(self->stream, b);  // Put the buffer back
}
