#include "PipeWireClient.hpp"
#include <unistd.h>

PipeWireClient::PipeWireClient()
{
  pw_init(nullptr, nullptr);
  std::println("[PipeWireClient] Library initialized");
}

PipeWireClient::~PipeWireClient()
{
  disconnect();
  pw_deinit();
}

bool PipeWireClient::connect(int fd, uint32_t node_id, std::function<void(const VideoFrame &)> callback)
{
  onFrameCallback = callback;
  this->fd = fd;

  if (!startLoop())
    return false;
  if (!configureCore())
    return false;
  configureStream();
  negotiateFormat(node_id);
  onConfigureEnd();

  return true;
}

bool PipeWireClient::startLoop()
{
  // Create a thread for PipeWire to process video packages and to not block our main thread
  loop = pw_thread_loop_new("pipewire-capture-loop", nullptr);
  context = pw_context_new(pw_thread_loop_get_loop(loop), nullptr, 0); // Manages memory, modules and plugins from our application side
  if (!(loop && context))
    return false;

  // Starts the PipeWire thread and immediately locks it, so it does not crash while we configure the format
  pw_thread_loop_start(loop);
  pw_thread_loop_lock(loop);
  return true;
}

void PipeWireClient::configureStream()
{
  // PipeWire manages media (audio, video, sound...). Here we define we want video management for node_id target
  pw_properties *props = pw_properties_new(
      PW_KEY_MEDIA_TYPE, "Video",
      PW_KEY_MEDIA_CATEGORY, "Capture",
      PW_KEY_MEDIA_ROLE, "Screen",
      nullptr);

  // Creates the communication channel
  stream = pw_stream_new(core, "RemoteDesktop Capture Stream", props);
  stream_events.version = PW_VERSION_STREAM_EVENTS;

  // Listeners
  stream_events.state_changed = onStreamStateChanged;
  stream_events.process = onStreamProcess; // Registers the event triggered on each frame generated by the GPU
  pw_stream_add_listener(stream, &stream_listener, &stream_events, this);
}

// Dictates how pixels are going to be sent from PipeWire to the application (eg. RBA, BGA, 60fps...). The GPU has been waiting for this contract
// BGAx -> 8bits for BLUE, 8bits GREEN, 8bits RED, 8bits for padding (null). It is the official format Linux draw the screen, so don't need to waste time converting it.
// Modern CPUs use 4 bytes blocks better than 3 bytes. They use SIMD registers.
// 1920(width) * 1080(heigth) * 4 bytes(BGRx) = 8.294.400 bytes
// 8.3 MB * 60 frames = 498 Megabytes/sec
void PipeWireClient::negotiateFormat(uint32_t node_id)
{
  uint8_t buffer[1024];
  // SPA -> Simple Plugin API, uses a dada package system called POD
  // POD -> Plain Old Data
  auto b = SPA_POD_BUILDER_INIT(buffer, sizeof(buffer));

  // Negotiation package
  // Tells PipeWire we want raw video, preferably at BGRx
  struct spa_video_info_raw raw_info = {};
  raw_info.format = SPA_VIDEO_FORMAT_BGRx;

  const spa_pod *param =
      (const spa_pod *)spa_format_video_raw_build(&b,
                                                  SPA_PARAM_EnumFormat,
                                                  &raw_info); // Tells PipeWire to convert the screen into BGRx format

  pw_stream_connect(stream,
                    PW_DIRECTION_INPUT, // We want to receive data, not to emit
                    node_id,
                    static_cast<pw_stream_flags>(PW_STREAM_FLAG_AUTOCONNECT | PW_STREAM_FLAG_MAP_BUFFERS),
                    &param, 1);
  // PW_STREAM_FLAG_MAP_BUFFERS -> tells PipeWire to map VRAM to RAM, so we can access frame.data
}

bool PipeWireClient::configureCore()
{
  // Tells context to connect with our File Descriptor. Duplicates it so we do not lose reference in case PipeWire thread closes it
  core = pw_context_connect_fd(context, dup(fd), nullptr, 0);
  if (!core)
  {
    pw_thread_loop_unlock(loop);
    return false;
  }

  core_events.version = PW_VERSION_CORE_EVENTS;
  core_events.error = onCoreError;
  pw_core_add_listener(core, &core_listener, &core_events, this);
  return true;
}

void PipeWireClient::onConfigureEnd()
{
  pw_thread_loop_unlock(loop);
  std::println("✅ [PipeWire] Stream created, format requested...");
}

void PipeWireClient::disconnect()
{
  if (loop)
  {
    pw_thread_loop_stop(loop);
    pw_thread_loop_lock(loop);
  }

  if (stream)
  {
    pw_stream_disconnect(stream);
    pw_stream_destroy(stream);
    stream = nullptr;
  }
  if (core)
  {
    pw_core_disconnect(core);
    core = nullptr;
  }
  if (context)
  {
    pw_context_destroy(context);
    context = nullptr;
  }

  if (loop)
  {
    pw_thread_loop_unlock(loop);
    pw_thread_loop_destroy(loop);
  }

  loop = nullptr;
}

void PipeWireClient::onStreamProcess(void *data)
{
  // Because PipeWire API is written in C, there's no instance context (no 'this' pointer)
  PipeWireClient *self = static_cast<PipeWireClient *>(data);

  // Gets next buffer from PipeWire ring buffers
  pw_buffer *b = pw_stream_dequeue_buffer(self->stream);
  if (!b)
    return; // No frame yet

  spa_buffer *buf = b->buffer;
  if (buf->datas[0].data != nullptr)
  {
    VideoFrame frame;
    // This address points directly to the mapped DMA-BUF at RAM
    frame.data = static_cast<uint8_t *>(buf->datas[0].data);
    frame.stride = buf->datas[0].chunk->stride;
    self->onFrameCallback(frame);
  }

  pw_stream_queue_buffer(self->stream, b); // Gives the buffer back so PipeWire can write next frame (zero-copy)
}

void PipeWireClient::onCoreError(void * /*data*/, uint32_t id, int /*seq*/, int /*res*/, const char *message)
{
  std::println(stderr, "❌ [PipeWire] Core critial error (id:{}): {}", id, message);
}

void PipeWireClient::onStreamStateChanged(void *data, pw_stream_state old_state, pw_stream_state state, const char *error)
{
  static const char *state_names[] = {"ERROR", "UNCONNECTED", "CONNECTING", "PAUSED", "STREAMING"};
  std::println("🌊 [PipeWire] Stream state changed: {} -> {}", state_names[old_state], state_names[state]);

  if (state == PW_STREAM_STATE_ERROR)
  {
    PipeWireClient *self = static_cast<PipeWireClient *>(data);
    if (self->context != nullptr)
    {
      std::println(stderr, "❌ [PipeWire] Error at Stream: {}", error ? error : "Unknown");
    }
  }
}

void PipeWireClient::onStreamParamChanged(void * /*data*/, uint32_t id, const spa_pod *param)
{
  if (param == nullptr)
    std::println(stderr, "❌ [PipeWire] Wayland server rejected the video format");
  return;
  if (id == SPA_PARAM_Format)
    std::println("✅ [PipeWire] Video format accepted by Wayland. Setting up frame sending...");
}
