#include "PipeWireClient.hpp"
#include <unistd.h>
#include <drm/drm_fourcc.h>
#include <spa/pod/vararg.h>

PipeWireClient::PipeWireClient()
{
  pw_init(nullptr, nullptr);
  std::println("[PipeWireClient] Library initialized");
}

PipeWireClient::~PipeWireClient()
{
  disconnect();
  pw_deinit();
}

bool PipeWireClient::connect(int fd, uint32_t node_id, std::function<void(const VideoFrame &)> callback)
{
  onFrameCallback = callback;
  this->fd = fd;

  if (!startLoop())
    return false;
  if (!configureCore())
    return false;
  configureStream();
  negotiateFormat(node_id);
  onConfigureEnd();

  return true;
}

bool PipeWireClient::startLoop()
{
  // Create a thread for PipeWire to process video packages and to not block our main thread
  loop = pw_thread_loop_new("pipewire-capture-loop", nullptr);
  context = pw_context_new(pw_thread_loop_get_loop(loop), nullptr, 0); // Manages memory, modules and plugins from our application side
  if (!(loop && context))
    return false;

  // Starts the PipeWire thread and immediately locks it, so it does not crash while we configure the format
  pw_thread_loop_start(loop);
  pw_thread_loop_lock(loop);
  return true;
}

bool PipeWireClient::configureCore()
{
  // Tells context to connect with our File Descriptor. Duplicates it so we do not lose reference in case PipeWire thread closes it
  core = pw_context_connect_fd(context, dup(fd), nullptr, 0);
  if (!core)
  {
    pw_thread_loop_unlock(loop);
    return false;
  }

  core_events.version = PW_VERSION_CORE_EVENTS;
  core_events.error = onCoreError;
  pw_core_add_listener(core, &core_listener, &core_events, this);
  return true;
}

void PipeWireClient::configureStream()
{
  // PipeWire manages media (audio, video, sound...). Here we define we want video management for node_id target
  pw_properties *props = pw_properties_new(
      PW_KEY_MEDIA_TYPE, "Video",
      PW_KEY_MEDIA_CATEGORY, "Capture",
      PW_KEY_MEDIA_ROLE, "Screen",
      nullptr);

  // Creates the communication channel
  stream = pw_stream_new(core, "RemoteDesktop Capture Stream", props);
  stream_events.version = PW_VERSION_STREAM_EVENTS;

  // Listeners
  stream_events.state_changed = onStreamStateChanged;
  stream_events.param_changed = onStreamParamChanged;
  stream_events.process = onStreamProcess; // Registers the event triggered on each frame generated by the GPU
  pw_stream_add_listener(stream, &stream_listener, &stream_events, this);
}

// To pass the frames to the encoder with zero copy into the RAM, we need DMA-BUFs (Direct Memory Access Buffers).
// PipeWire provides a File Descriptor pointing to VRAM. FFmpeg uses AV_PIX_FMT_DRM_PRIME format to reed this FD on its pipeline.
void PipeWireClient::negotiateFormat(uint32_t node_id)
{
  uint8_t buffer[1024];
  spa_pod_builder b = SPA_POD_BUILDER_INIT(buffer, sizeof(buffer));

  const struct spa_pod *params[1];
  params[0] = (spa_pod *)
      spa_pod_builder_add_object(
          &b,
          SPA_TYPE_OBJECT_Format, SPA_PARAM_EnumFormat,
          SPA_FORMAT_mediaType, SPA_POD_Id(SPA_MEDIA_TYPE_video),
          SPA_FORMAT_mediaSubtype, SPA_POD_Id(SPA_MEDIA_SUBTYPE_raw),
          SPA_FORMAT_VIDEO_format, SPA_POD_CHOICE_ENUM_Id(4, SPA_VIDEO_FORMAT_RGBx, SPA_VIDEO_FORMAT_RGBx, SPA_VIDEO_FORMAT_RGBA, SPA_VIDEO_FORMAT_BGRx));

  // Connecting to the stream.
  // We REMOVED PW_STREAM_FLAG_MAP_BUFFERS because mapping DMA-BUFs to CPU memory
  // fails in PipeWire and we only want zero-copy hardware encoding anyway.
  pw_stream_connect(
      stream,
      PW_DIRECTION_INPUT,
      node_id,
      (enum pw_stream_flags)(PW_STREAM_FLAG_AUTOCONNECT),
      params, 1);
}

void PipeWireClient::onConfigureEnd()
{
  pw_thread_loop_unlock(loop);
  std::println("✅ [PipeWire] Stream created, format requested...");
}

void PipeWireClient::disconnect()
{
  if (loop)
    pw_thread_loop_stop(loop);
  if (stream)
  {
    pw_stream_disconnect(stream);
    pw_stream_destroy(stream);
    stream = nullptr;
  }
  if (core)
  {
    pw_core_disconnect(core);
    core = nullptr;
  }
  if (context)
  {
    pw_context_destroy(context);
    context = nullptr;
  }
  if (loop)
  { // We need to destroy everything else first wit the loop paused
    pw_thread_loop_destroy(loop);
    loop = nullptr;
  }
}

void PipeWireClient::onCoreError(void * /*data*/, uint32_t id, int /*seq*/, int /*res*/, const char *message)
{
  std::println(stderr, "❌ [PipeWire] Core critial error (id:{}): {}", id, message);
}

void PipeWireClient::onStreamStateChanged(void *data, pw_stream_state old_state, pw_stream_state state, const char *error)
{
  static const char *state_names[] = {"ERROR", "UNCONNECTED", "CONNECTING", "PAUSED", "STREAMING"};
  std::println("🌊 [PipeWire] Stream state changed: {} -> {}", state_names[old_state], state_names[state]);

  PipeWireClient *self = static_cast<PipeWireClient *>(data);

  if (state == PW_STREAM_STATE_PAUSED)
    pw_stream_set_active(self->stream, true);
  else if (state == PW_STREAM_STATE_ERROR && self->context != nullptr)
    std::println(stderr, "❌ [PipeWire] Error at Stream: {}", error ? error : "Unknown");
}

// Called after Wayland accepted the video format config and before GPU sent the first frame
// connect() -> state changed to 'CONNECTING' -> PipeWire gets the request and accepts it -> onStreamParamChanged() -> instantiate encoder
void PipeWireClient::onStreamParamChanged(void *data, uint32_t id, const spa_pod *param)
{
  PipeWireClient *self = static_cast<PipeWireClient *>(data);

  if (param == nullptr || id != SPA_PARAM_Format)
    return;

  struct spa_video_info_raw info;

  if (int ret = spa_format_video_raw_parse(param, &info) < 0)
  {
    std::println("[PipeWireClient] Error parsing video format. Code: {}", ret);
    return;
  }

  self->width = info.size.width;
  self->height = info.size.height;
  self->format = info.format;
  self->fps = (info.framerate.denom > 0 && info.framerate.num > 0) ? info.framerate.num / info.framerate.denom : 144;
  self->drmModifier = info.modifier;

  uint8_t buffer[1024];
  spa_pod_builder b = SPA_POD_BUILDER_INIT(buffer, sizeof(buffer));
  const struct spa_pod *params[1];

  params[0] = (spa_pod *)
      spa_pod_builder_add_object(
          &b,
          SPA_TYPE_OBJECT_ParamBuffers, SPA_PARAM_Buffers,
          SPA_PARAM_BUFFERS_buffers, SPA_POD_CHOICE_RANGE_Int(8, 2, 32),
          SPA_PARAM_BUFFERS_blocks, SPA_POD_Int(1),
          SPA_PARAM_BUFFERS_size, SPA_POD_Int(self->width * self->height * 4),
          SPA_PARAM_BUFFERS_stride, SPA_POD_Int(self->width * 4),
          SPA_PARAM_BUFFERS_dataType, SPA_POD_CHOICE_FLAGS_Int((1 << SPA_DATA_DmaBuf) | (1 << SPA_DATA_MemFd)));

  pw_stream_update_params(self->stream, params, 1);
  pw_stream_set_active(self->stream, true);
}

// Called once every frame
void PipeWireClient::onStreamProcess(void *data)
{
  PipeWireClient *self = static_cast<PipeWireClient *>(data);
  struct pw_buffer *b = pw_stream_dequeue_buffer(self->stream);
  if (!b)
    return;

  struct spa_buffer *buf = b->buffer;
  VideoFrame frame = {
      .type = FrameMemoryType::MemFd,
      .fd = dup(buf->datas[0].fd),
      .width = self->width,
      .height = self->height,
      .stride = buf->datas[0].chunk->stride,
      .fps = self->fps,
      .drmModifier = self->drmModifier};

  if (buf->datas[0].chunk->size == 0)
  {
    pw_stream_queue_buffer(self->stream, b);
    return;
  }

  switch (buf->datas[0].type)
  {
  case SPA_DATA_DmaBuf:
  case SPA_ID_INVALID:
    frame.type = FrameMemoryType::DmaBuf;
    static int frameCount = 0;
    frameCount++;
    if (frameCount % 60 == 0)
      std::println("📸 [PipeWireClient] Captured and sent {} frames (GPU DmaBuf) to H264Encoder...", frameCount);
    break;
  case SPA_DATA_MemFd:
    static int frameCountMemFd = 0;
    frameCountMemFd++;
    if (frameCountMemFd % 144 == 0)
      std::println("📸 [PipeWireClient] Captured and sent {} frames (MemFd) to H264Encoder...", frameCountMemFd);
    break;
  default:
    break;
  }

  if (self->onFrameCallback)
    self->onFrameCallback(frame);

  pw_stream_queue_buffer(self->stream, b);
}
